/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createWorkbookFunctionResultFromDiscriminatorValue, serializeWorkbookFunctionResult, type WorkbookFunctionResult } from '../../../../../../../models/';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '../../../../../../../models/oDataErrors/';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter, UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SydPostRequestBody}
 */
export function createSydPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSydPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
export function deserializeIntoSydPostRequestBody(sydPostRequestBody: Partial<SydPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "cost": n => { sydPostRequestBody.cost = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "life": n => { sydPostRequestBody.life = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "per": n => { sydPostRequestBody.per = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "salvage": n => { sydPostRequestBody.salvage = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
export function serializeSydPostRequestBody(writer: SerializationWriter, sydPostRequestBody: Partial<SydPostRequestBody> | undefined = {}) : void {
    writer.writeObjectValue("cost", sydPostRequestBody.cost);
    writer.writeObjectValue("life", sydPostRequestBody.life);
    writer.writeObjectValue("per", sydPostRequestBody.per);
    writer.writeObjectValue("salvage", sydPostRequestBody.salvage);
    writer.writeAdditionalData(sydPostRequestBody.additionalData);
}
export interface SydPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The cost property
     */
    cost?: UntypedNode;
    /**
     * The life property
     */
    life?: UntypedNode;
    /**
     * The per property
     */
    per?: UntypedNode;
    /**
     * The salvage property
     */
    salvage?: UntypedNode;
}
/**
 * Provides operations to call the syd method.
 */
export interface SydRequestBuilder extends BaseRequestBuilder<SydRequestBuilder> {
    /**
     * Invoke action syd
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WorkbookFunctionResult>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     */
     post(body: SydPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<WorkbookFunctionResult | undefined>;
    /**
     * Invoke action syd
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SydPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SydRequestBuilderUriTemplate = "{+baseurl}/drives/{drive%2Did}/items/{driveItem%2Did}/workbook/functions/syd";
/**
 * Metadata for all the requests in the request builder.
 */
export const SydRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SydRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createWorkbookFunctionResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSydPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
